### ISSUE TITLE
Haret Queue datatype as replacement for amqp/mqtt based queues

### ISSUE THREAD

**Issue by stephanbuys** [vmware/haret#110]
Hi, awesome, exciting development!

We're in search of a lightweight queue to pass messages between containers, not wanting to go the kafka/jvm/zookeeper route. 

Would haret's queue be suitable?

Regards,
Stephan

**Comment by andrewjstone** [comment]
Hi @stephanbuys,

The haret queue really isn't meant for that. It's just a leaf in the tree stored by a haret namespace and is backed by a VecDeque. It's more meant for small metadata. You really wouldn't want to store more than 1 MB of data in such a queue.

In the future it should be possible to build a consistent, distributed queue on top of haret, and that is something I'd like to do, but Haret isn't production ready yet, and quite a few things are likely to change in the near future.
