### ISSUE TITLE
Finish setting up travis continuous integration

### ISSUE THREAD

**Issue by erickt** [vmware/haret#112]
Hello! I see you have a travis config file, but it doesn't look like you have the [integration configured](https://travis-ci.org/vmware/haret). I think you can turn it on on this [page](https://travis-ci.org/vmware/haret/settings), but you might also need to also enable it on the [integrations page](https://github.com/vmware/haret/settings/installations).

**Comment by andrewjstone** [comment]
HI @erickt,
Unfortunately I don't have permissions to enable it on this repo. I'll find the right person to flick the switch then I'll update the README to show the badge. Thanks for the kick in the right direction.

**Comment by andrewjstone** [comment]
Done! Thanks for the push @erickt and @jrgarcia for pointing me in the right direction inside VMware.
