### ISSUE TITLE
debugger_cli binary has no way to be built

### ISSUE THREAD

**Issue by erickt** [vmware/haret#117]
Looking through the repository, `src/bin/debugger_cli.rs` is not configured to be built. I tried to add it in, but it's missing some dependencies. First there is reference to a [distill](https://github.com/vmware/haret/blob/master/src/bin/debugger_cli.rs#L10) crate, that does not appear in the local directory or in crates.io. Second, there's reference to [debugger_shared](https://github.com/vmware/haret/blob/master/src/bin/debugger_cli.rs#L20), which doesn't exist in the directory.

**Comment by andrewjstone** [comment]
Once upon a time there was a property based state machine testing library called `distill` that recorded all messages through the scheduler during testing. The debugger would use those traces to allows stepping forward and backward through them and showing diffs of the states of different replicas. While handy as an application level test debugger it was a bit to maintain and wasn't exactly a bastion of good design. It was abandoned in favor of the `quickcheck` crate.

I actually removed all traces to it finally in the `enum_fsm` branch the other day, as it appears I never completed the cleanup.

**Comment by erickt** [comment]
Great! I'll ignore these files then.

**Comment by andrewjstone** [comment]
This file doesn't exist anymore
