### ISSUE TITLE
Missing instructions on how to regenerate protobuf message struct

### ISSUE THREAD

**Issue by erickt** [vmware/haret#119]
If we end up doing #118, then we need to regenerate the `messages.rs` file, but I'm not sure how to do that. Could instructions be written up for this?

**Comment by andrewjstone** [comment]
Hi @erickt 

I added a [PR](https://github.com/vmware/haret/pull/120) for a brief doc on this. Let me know if it works for you.

**Comment by erickt** [comment]
Works for me!
