### ISSUE TITLE
README - possible issue with cargo run --bin haret-admin

### ISSUE THREAD

**Issue by MarkSwanson** [vmware/haret#140]
haret$ rlwrap cargo run --bin haret-admin 127.0.0.1:2001
.../haret/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace

I'm running a slightly old nightly (cargo 0.20.0-nightly (397359840 2017-05-18)) so apologies if this is my fault (my environment isn't stable).

But in case Cargo has updated since you last tested your README, and in case this helps someone the solution here is:

haret$ rlwrap ./target/debug/haret-admin 127.0.0.1:2001

**Comment by andrewjstone** [comment]
Hi @MarkSwanson. This breakage happened due to a refactoring into [workspaces](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html) a couple of months back. I have updated the docs to reflect the new usage.
